;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
com3-init.lua=python C:\cmder\meekdai\luatool.py --port COM3 --src init.lua -r
luatool=python C:\cmder\meekdai\luatool.py $*
com=python C:\cmder\meekdai\miniterm.py $*
st= C:\SublimeText\sublime_text.exe  $*
kjj= vim C:\cmder\config\user-aliases.cmd
lsup= c:\cmder\meekdai\getletter_drive.cmd
gw=cd /d c:\meekdai
gd=cd /d C:\Users\Meekdai\Desktop
7z=C:\cmder\meekdai\7z.exe $*
vimrc= vim C:\cmder\vendor\vim\_vimrc 
